# Generated by Django 6.1.1 on 2026-09-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_redefinicaosenhamedico'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pacienteconvenio',
            name='paciente_convenio_unico',
        ),
        migrations.RemoveField(
            model_name='pacienteconvenio',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='pacienteconvenio',
            name='paciente',
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
        migrations.DeleteModel(
            name='Convenio',
        ),
        migrations.DeleteModel(
            name='PacienteConvenio',
        ),
    ]
