# Generated by Django 6.1.1 on 2026-09-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0003_remove_pacienteconvenio_paciente_convenio_unico_and_more")]

    operations = [
        migrations.RenameField(model_name="prontuario", old_name="alergias", new_name="avaliacao"),
        migrations.RenameField(model_name="prontuario", old_name="historico_medico", new_name="objetivo"),
        migrations.RenameField(model_name="prontuario", old_name="observacoes", new_name="plano"),
        migrations.AddField(model_name="prontuario", name="subjetivo", field=models.TextField(blank=True)),
    ]
